[package]
name = "decay"
version = "0.1.0"
authors = ["Piotr Podusowski <ext-lux-pp@ad.datcon.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "*"
piston_window = "*"