on:
  workflow_call:
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev 
